#!/usr/bin/env python3
"""
loop/status.py — assemble loop/STATUS.md, the agent's start-of-tick situational view.

The ralph agent used to read frozen knob values out of prose docs (PROMPT.md/IDEAS.md)
that drifted from engine/march_params.json — it was steering by numbers that no longer
existed. Per the harness-engineering principle "agent legibility is the goal", this
generates ONE git-ignored file, regenerated every tick, that shows the LIVE state:

  - Live knobs      — engine/march_params.json values next to engine.march.PARAM_BOUNDS
                      ranges (single source of truth; nothing to drift).
  - Trend           — recent ticks' d_score/d_fine/d_fidelity/d_diag/d_ink + best d_fine.
  - Guard verdict   — why last tick was kept/reverted (from loop/.guard_feedback).
  - Pointers        — the comparison montage + the experiment digest.

Invoked at the end of loop/score_tick.sh (after metrics.jsonl is appended).

Usage:
    python loop/status.py            # newest iter in metrics.jsonl
    python loop/status.py <iter>
"""
import sys
import json
import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

METRICS = REPO / "loop" / "metrics.jsonl"
PARAMS = REPO / "engine" / "march_params.json"
FEEDBACK = REPO / "loop" / ".guard_feedback"
DIGEST = REPO / "loop" / "EXPERIMENT_DIGEST.md"
MONTAGE = REPO / "loop" / "output" / "_latest_compare.png"
STATUS = REPO / "loop" / "STATUS.md"

TREND_KEYS = ("d_score", "d_fine", "d_fidelity", "d_diag", "d_ink")


def _rows():
    if not METRICS.exists():
        return []
    out = []
    for ln in METRICS.read_text().splitlines():
        ln = ln.strip()
        if ln:
            try:
                out.append(json.loads(ln))
            except json.JSONDecodeError:
                pass
    return out


def _fmt(v, spec="{:.3f}"):
    return spec.format(v) if isinstance(v, (int, float)) else "?"


def _knobs_table():
    """Live JSON values beside their search/clamp bounds — no frozen copies."""
    try:
        from engine.march import PARAM_BOUNDS, PARAM_NAMES
    except Exception:
        PARAM_BOUNDS, PARAM_NAMES = {}, ()
    live = {}
    if PARAMS.exists():
        try:
            live = json.loads(PARAMS.read_text())
        except (OSError, ValueError):
            live = {}
    names = PARAM_NAMES or tuple(sorted(live))
    lines = ["| knob | live value | bounds (lo–hi) |",
             "|---|---|---|"]
    for n in names:
        lo, hi = PARAM_BOUNDS.get(n, ("?", "?"))
        val = live.get(n, "?")
        val = f"{val:g}" if isinstance(val, (int, float)) else val
        rng = f"{lo:g}–{hi:g}" if isinstance(lo, (int, float)) else f"{lo}–{hi}"
        lines.append(f"| `{n}` | {val} | {rng} |")
    return "\n".join(lines)


def _trend_table(rows, n=8):
    recent = rows[-n:]
    head = "| iter | " + " | ".join(TREND_KEYS) + " |"
    sep = "|" + "---|" * (len(TREND_KEYS) + 1)
    body = []
    for r in recent:
        cells = [str(r.get("iter", "?"))]
        for k in TREND_KEYS:
            spec = "{:.0f}" if k == "d_score" else "{:.3f}"
            cells.append(_fmt(r.get(k), spec))
        body.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, sep, *body])


def build(iter_num=None):
    rows = _rows()
    cur = None
    if rows:
        if iter_num is not None:
            cur = next((r for r in reversed(rows) if r.get("iter") == iter_num), None)
        cur = cur or rows[-1]

    fine_rows = [(r.get("iter"), r["d_fine"]) for r in rows
                 if isinstance(r.get("d_fine"), (int, float))]
    best = max(fine_rows, key=lambda t: t[1]) if fine_rows else None

    parts = ["# WAVEFRONT loop — live status",
             "",
             "_Generated by `loop/status.py` after each tick. Do not edit by hand; "
             "do not commit (git-ignored). This is your start-of-tick situational view._",
             ""]

    if cur:
        parts += [f"**Latest scored tick:** iter {cur.get('iter','?')} — "
                  f"d_score={_fmt(cur.get('d_score'),'{:.0f}')}, "
                  f"d_fine={_fmt(cur.get('d_fine'))}, "
                  f"d_fidelity={_fmt(cur.get('d_fidelity'))}, "
                  f"d_diag={_fmt(cur.get('d_diag'))}, "
                  f"d_ink={_fmt(cur.get('d_ink'))}.", ""]
    if best:
        parts += [f"**Best d_fine so far:** {best[1]:.3f} at iter {best[0]} "
                  f"(target ≈0.73). Steer by d_fine while keeping d_score=100.", ""]

    parts += ["## Live knobs (engine/march_params.json)",
              "",
              "These ARE the current values — tune by editing that JSON. Bounds are "
              "`engine.march.PARAM_BOUNDS`; moves outside them are clamped.",
              "",
              _knobs_table(),
              ""]

    parts += ["## Recent trend", "", _trend_table(rows), ""]

    if FEEDBACK.exists():
        parts += ["## Last-tick guard verdict", "", FEEDBACK.read_text().strip(), ""]

    pointers = [f"- Comparison montage (Read it): `{MONTAGE.relative_to(REPO)}` "
                f"— source | current | best | artist target, metrics annotated."]
    if DIGEST.exists():
        pointers.append(f"- Distilled experiment digest: `{DIGEST.relative_to(REPO)}` "
                        f"— what's helped / been ruled out / open threads.")
    parts += ["## Pointers", "", *pointers, ""]

    STATUS.write_text("\n".join(parts))
    return STATUS


def main():
    p = argparse.ArgumentParser()
    p.add_argument("iter", nargs="?", type=int, default=None)
    a = p.parse_args()
    try:
        out = build(a.iter)
    except Exception as e:   # never break a tick
        sys.stderr.write(f"[status] skipped: {e}\n")
        return 0
    print(f"[status] wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
